name: melon-ticket-check
on:
  workflow_dispatch: # <-- 3번째 줄에 이 코드를 꼭 넣어주셔야 버튼이 생깁니다!
  schedule:
    - cron: '*/5 * * * *' # # 5분마다 실행

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 213346          # <-- 내 공연 ID로 변경
          schedule-id: 100001         # <-- 내 회차 ID로 변경
          seat-id: test                # <-- 내 좌석 등급 ID로 변경
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '포도알 떴다! 예매창으로 뛰어라! 🏃‍♂️'
